### ISSUE TITLE
[theme editor]: [no colors setting possible]

### ISSUE THREAD

**Issue by MasterXYW** [Scrounger/ioBroker.vis-materialdesign#150] opened 2021-03-01 10:08 UTC
I install the new material design widget adapter 0.4.2. I have no possibility to change the color with the theme editor because there are no buttons and only standard color 0. The fonts work. I tried to reinstall an earlier version but nothing happens.

![Farben dunkel](https://user-images.githubusercontent.com/79838818/109482412-4068a580-7a7e-11eb-8f4d-9b37f63235a5.PNG)

**Comment by Scrounger** [comment] 2021-03-01 10:12
think this is caused by a mix between version 0.5.x and 0.4.x.

Please install the current version from github directly or wait until 0.5.x is released in stable.

**Closed by Scrounger** 2021-03-01 10:12 UTC
