### ISSUE TITLE
Switches, Buttons, Lists not working (boolean)

### ISSUE THREAD

**Issue by Strobelix80** [Scrounger/ioBroker.vis-materialdesign#5] opened 2019-10-20 16:23 UTC
Since 0.1.2 Switches, Lists and some Buttons don‘t send commands to objects in ioBroker. They only show their states.
for example:
switch as boolean with off=false and on=true is not working.
Same with toggle
Toggle vertical works instead

**Comment by Scrounger** [comment] 2019-10-21 15:45
Can not confirm this. all work as expected.
Please rebuild completly the widgets, means add new ones. For boolean toggle use toggleType 'boolean'

**Comment by Scrounger** [comment] 2019-10-24 13:16
Please give a feedback!

**Comment by Strobelix80** [comment] 2019-10-25 05:53
I‘ve tried the update again.
Same issues appearing.
Downgrade to 0.1.1 fixes the issues
I have to try update and changing the buttons again

**Comment by Strobelix80** [comment] 2019-10-26 12:21
Tried it again.
I have updated to 0.1.2
Switch (boolean) shows the right state but doesn't send a command.
Downgrade to 0.1.1
Switch works fine

**Comment by Scrounger** [comment] 2019-10-26 14:39
![working](https://user-images.githubusercontent.com/6370451/67621280-e400d080-f80e-11e9-8775-f8791332c49f.gif)

As you can see, all wok as expected - sending and receiving commands.
I didnt get any ohter reponse with your descibed behaviour. So think its not a problem of the adapter. Did you check other widgets, if you have there the same problem?

**Comment by Strobelix80** [comment] 2019-10-26 15:56
![buttontest](https://user-images.githubusercontent.com/38631546/67622345-c422da00-f819-11e9-91b1-49af6cc91460.gif)

I created a completely new vis project.
Still the same issues.
Every other switch works fine.

**Comment by Scrounger** [comment] 2019-10-27 20:43
Which browser do you use?

**Comment by Strobelix80** [comment] 2019-10-27 20:44
Safari macos and ios

**Comment by Scrounger** [comment] 2019-10-27 20:47
Do you have the possibility to test it with another browser? I dont have safari.

**Comment by Strobelix80** [comment] 2019-11-03 09:34
Same on Chrome
I‘ll try a completely new and clean ioBroker installation

**Comment by Scrounger** [comment] 2019-11-04 17:09
Think you dont need this. Please show the settings of your switch, i have an idea.

**Comment by Strobelix80** [comment] 2019-11-04 17:15
First I have to update again. But i tried any possibilities. Of course i‘ve set the switch to boolean and tried true/false in any constellation

**Comment by Scrounger** [comment] 2019-11-04 17:19
if you use toggleType = boolean, then you dont need to add somthing to valueOff / valueOn option.
But the datapoint must be a real boolean! Prehaps some script wirte 'true' / 'false' -> thats a string not a boolean.

**Comment by Strobelix80** [comment] 2019-11-04 17:21
My datapoints are real booleans for sure, but i‘ll try it again

**Comment by Strobelix80** [comment] 2019-11-04 19:05
![368A65D5-0F20-46A1-9832-CE86770329F3](https://user-images.githubusercontent.com/38631546/68149550-5d4ea080-ff3e-11e9-877e-cca94bb553c9.jpeg)
![833496DA-EE06-43F3-AF2D-8285616491BD](https://user-images.githubusercontent.com/38631546/68149551-5de73700-ff3e-11e9-86c6-45a1ca32c91e.jpeg)

My settings

**Comment by sigi2345** [comment] 2019-11-04 23:05
> ![368A65D5-0F20-46A1-9832-CE86770329F3](https://user-images.githubusercontent.com/38631546/68149550-5d4ea080-ff3e-11e9-877e-cca94bb553c9.jpeg)
> ![833496DA-EE06-43F3-AF2D-8285616491BD](https://user-images.githubusercontent.com/38631546/68149551-5de73700-ff3e-11e9-86c6-45a1ca32c91e.jpeg)
> 
> My settings

state if not true value : an?

**Comment by Strobelix80** [comment] 2019-11-05 06:56
> > ![368A65D5-0F20-46A1-9832-CE86770329F3](https://user-images.githubusercontent.com/38631546/68149550-5d4ea080-ff3e-11e9-877e-cca94bb553c9.jpeg)
> > ![833496DA-EE06-43F3-AF2D-8285616491BD](https://user-images.githubusercontent.com/38631546/68149551-5de73700-ff3e-11e9-86c6-45a1ca32c91e.jpeg)
> > My settings
> 
> state if not true value : an?

Doesn‘t matter. No change in behavior

**Comment by DevChannel-de** [comment] 2019-11-07 07:40
I'm assuming that the point macos and/or ios could be the right direction of further investigation.

I tested the bool switch with Chrome@ios and I can confirm the same issue.
When I call exactly the same view on Chrome@Win10 it works fine.

**Comment by Scrounger** [comment] 2019-11-10 15:23
Please test the actual master verison 0.1.12.
If it is still not working, upload console log file, after pressing / switching!

**Comment by Strobelix80** [comment] 2019-11-10 18:08
cannot find 0.1.12?
Where can i get that?

**Comment by DevChannel-de** [comment] 2019-11-10 19:01
@Strobelix80: Please try to take "https://github.com/Scrounger/ioBroker.vis-materialdesign" as update URL in iobroker admin->adapter section.

After such update I see still version "0.1.5" but the update was probably successful...
AND: after my first tests I can confirm that this issue doesn't occur anymore! :-)

**Comment by Strobelix80** [comment] 2019-11-10 19:18
That‘s it!
Works great after updating to this version

**Comment by Scrounger** [comment] 2019-11-10 20:49
Great!
Reason is that safari not support the navigator virbrate api. Just find it out because i get the right consol log ;)
So im closing this

**Closed by Scrounger** 2019-11-10 20:49 UTC
